### ISSUE TITLE
no memory when NGX_HTTP_SLA_MAX_TIMINGS_LEN increased

### ISSUE THREAD

**Issue by fsalum** [goldenclone/nginx-sla#9]
I'm getting the error below when I increase the TIMINGS and HTTP length to 64

2015/06/05 21:51:09 [crit] 4065#0: ngx_slab_alloc() failed: no memory

And I'm having segmentation fault with sla_pool enabled and NGX_HTTP_SLA_MAX_COUNTERS_LEN set to 256. If I drop the length then I miss some metrics since this server run many upstreams.

**Comment by abbat** [comment]
We have no experience with so large NGX_HTTP_SLA_MAX_COUNTERS_LEN count. I think the problem is in line [818 in ngx_http_sla.c](https://github.com/goldenclone/nginx-sla/blob/master/ngx_http_sla.c#L818) - too much memory allocation for result. If LinkedIn have a patch we will happy to accept it :)

**Comment by angryoxen** [comment]
I'm not at all familiar with this code, but it seems like ngx_http_sla_status should check the return value from ngx_http_sla_status_handler and return NGX_CONF_ERROR on failures.  That doesn't fix the memory allocation problem, but it should fix the ensuing segfaults.  Assuming I can duplicate and this approach works, would you accept a pull req with that limited scope?

**Comment by abbat** [comment]
ngx_http_sla_status does not call ngx_http_sla_status_handler - it just set callback pointer to function. But if you can fix segfaults - yes, PR welcome!

**Comment by angryoxen** [comment]
of course (slaps forehead).  I'll see what I can do.

**Comment by abbat** [comment]
Also you can try to increase sysctl-s kernel.shmmax and kernel.shmall for slab allocation.

**Comment by fsalum** [comment]
he is the backtrace from the segfault when uncommenting the sla_pool lines:

```
#0  ngx_shmtx_lock (mtx=0x50) at src/core/ngx_shmtx.c:78
        i = <value optimized out>
        n = <value optimized out>
#1  0x00000000004cf0be in ngx_http_sla_processor (r=0xe1ffa0) at /usr/src/debug/nginx-1.6.3/nginx-sla-master/ngx_http_sla.c:958
        i = <value optimized out>
        ms = <value optimized out>
        time = <value optimized out>
        status = <value optimized out>
        alias = <value optimized out>
        counter = <value optimized out>
        config = 0xd87e50
        state = <value optimized out>
#2  0x0000000000446af7 in ngx_http_log_request (r=0xe1ffa0, rc=<value optimized out>) at src/http/ngx_http_request.c:3508
        i = <value optimized out>
        n = 2
        log_handler = 0xe26810
#3  ngx_http_free_request (r=0xe1ffa0, rc=<value optimized out>) at src/http/ngx_http_request.c:3455
        log = 0xd4a7a0
        pool = <value optimized out>
        linger = {l_onoff = 537554533, l_linger = 538976288}
        cln = <value optimized out>
        ctx = <value optimized out>
#4  0x0000000000446d13 in ngx_http_close_request (r=0xe1ffa0, rc=0) at src/http/ngx_http_request.c:3402
        c = 0x7f9e1b858958
#5  0x0000000000447d7a in ngx_http_lingering_close_handler (rev=0xe56c78) at src/http/ngx_http_request.c:3269
        n = <value optimized out>
        timer = <value optimized out>
        c = 0x7f9e1b858958
        r = 0xe1ffa0
        buffer = "(key, 0)\n        local new_ver, err = dict:incr(key, 1)\n        if not new_ver then\n", ' ' <repeats 12 times>, "errlog(\"failed to publish new peers version: \", err)\n   \226\222\200]9\000\000\000\n\n      \000\020-E�\177\000\000rsion = \000\020-E�\177\000\000\026\000\000\000\000\000\000\000�<"...
#6  0x000000000042dd66 in ngx_event_process_posted (cycle=<value optimized out>, posted=0x719c48) at src/event/ngx_event_posted.c:40
        ev = <value optimized out>
#7  0x0000000000433bb8 in ngx_worker_process_cycle (cycle=0xd3ca60, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:816
        worker = <value optimized out>
        i = <value optimized out>
        c = <value optimized out>
#8  0x0000000000432247 in ngx_spawn_process (cycle=0xd3ca60, proc=0x433af0 <ngx_worker_process_cycle>, data=0x10, name=0x4d4993 "worker process", respawn=16) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = <value optimized out>
#9  0x00000000004349ba in ngx_reap_children (cycle=0xd3ca60) at src/os/unix/ngx_process_cycle.c:627
        i = <value optimized out>
        live = <value optimized out>
        n = <value optimized out>
        ch = {command = 2, pid = 24718, slot = 16, fd = -1}
        ccf = <value optimized out>
#10 ngx_master_process_cycle (cycle=0xd3ca60) at src/os/unix/ngx_process_cycle.c:180
        title = <value optimized out>
        p = <value optimized out>
        size = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        i = <value optimized out>
        n = <value optimized out>
        sigio = 0
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 0, tv_usec = 13879928}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <value optimized out>
        delay = 0
        ls = <value optimized out>
        ccf = 0xd3daa8
#11 0x0000000000416636 in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:407
        i = <value optimized out>
        log = <value optimized out>
        cycle = 0xd3ca60
        init_cycle = {conf_ctx = 0x0, pool = 0xd3be70, log = 0x715000, new_log = {log_level = 0, file = 0x0, connection = 0, handler = 0, data = 0x0, action = 0x0, next = 0x0},
          log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0, reusable_connections_queue = {prev = 0x0, next = 0x0}, listening = {elts = 0x0, nelts = 0, size = 0,
            nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0,
            pool = 0x0}, shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0,
          read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {len = 21, data = 0x7fff452d2852 "ss"}, conf_param = {len = 0, data = 0x0}, conf_prefix = {len = 11,
            data = 0x7fff452d2852 "ss"}, prefix = {len = 11, data = 0x4d0b0b "/etc/nginx/"}, lock_file = {len = 0, data = 0x0}, hostname = {len = 0, data = 0x0}}
        ccf = 0xd3daa8
```

**Comment by abbat** [comment]
Hmm... Very interesting.
Would you  try to increase sysctl-s kernel.shmmax and kernel.shmall and test again?

**Comment by abbat** [comment]
Would you test version from abbat/nginx-sla@c65b292 ?

**Comment by fsalum** [comment]
Sure, I will test it today.

**Comment by fsalum** [comment]
Looks like it didn't fix the issue yet.

```
Jun 19 18:59:10 <host> kernel: [9978291.309828] nginx[26554]: segfault at 50 ip 000000000042154d sp 00007fff1bd77d70 error 4 in nginx[400000+100000]

kernel.shmmax = 4294967295
kernel.shmall = 20971520
```

I'm compiling it with these parameters:

```
--with-cc-opt="%{optflags} $(pcre-config --cflags) -I /export/apps/openssl/include -L /export/apps/openssl/lib -DNGX_HTTP_SLA_MAX_COUNTERS_LEN=32 -DNGX_HTTP_SLA_MAX_HTTP_LEN=64 -DNGX_HTTP_SLA_MAX_TIMINGS_LEN=64" \
```

I have 23 upstreams, and around 48 timings and http status defined in total.

**Comment by abbat** [comment]
Would you provide more info (OS, x64 or i386, all steps to compile, config and run nginx) to reproduce in test environment?
